services:
# infra
  logger:
    hostname: logger
    container_name: logger
    image: amir20/dozzle:latest
    networks:
      - ironnet
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    image: haproxy:latest
    hostname: haproxy
    container_name: haproxy
    networks:
      - ironnet
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936" # Stats UI
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./.ca/combined.pem:/etc/ssl/certs/combined.pem:ro
  maildev:
    image: maildev/maildev
    hostname: maildev
    container_name: maildev
    restart: always
    environment:
      - TZ=America/New_York
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_MAIL_DIRECTORY=/var/data
    networks:
      - ironnet
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    volumes:
      - ./maildev/data:/var/data
  mockserver:
    image: mockserver/mockserver:5.15.0
    hostname: mockserver
    container_name: mockserver
    networks:
      - ironnet
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./mockserver/config:/config

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: gitlab
    container_name: gitlab
    networks:
      - ironnet
    ports:
      - '8088:80'
    env_file:
      - ./gitlab.env
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab

  nifi:
    hostname: nifi
    container_name: nifi
    image: apache/nifi:latest
    env_file:
      - ./nifi.env
    networks:
      - ironnet
    ports:
      - '8443:8443'
    volumes:
      - nifi_local_i1:/opt/nifi/nifi-current

volumes:
  nifi_local_i1:

networks:
  ironnet:
    driver: bridge
    name: ironnet
